#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 24, 2025 07:42:29 PM EET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import bloggerup_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+383+106")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.but47 = tk.Button(self.top)
        self.but47.place(relx=0.267, rely=0.756, height=76, width=337)
        self.but47.configure(activebackground="#d9d9d9")
        self.but47.configure(activeforeground="black")
        self.but47.configure(background="#d9d9d9")
        self.but47.configure(disabledforeground="#a3a3a3")
        self.but47.configure(foreground="#000000")
        self.but47.configure(highlightbackground="#d9d9d9")
        self.but47.configure(highlightcolor="#000000")
        self.but47.configure(text='''http://vasiliyps.my-style.in/up.html''')

def start_up():
    bloggerup_support.main()

if __name__ == '__main__':
    bloggerup_support.main()




